# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  de: Freund
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: interview-task-de
    meta.helm.sh/release-namespace: interview
  labels:
    app.kubernetes.io/managed-by: Helm
  name: hello-world-de
  namespace: interview

