# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: interview-task-de
    meta.helm.sh/release-namespace: interview
  creationTimestamp: "2022-12-29T10:13:00Z"
  generation: 1
  labels:
    app: hello
    app.kubernetes.io/managed-by: Helm
    svc-name: hello-world-de
  name: hello-world-de
  namespace: interview
  resourceVersion: "2165894"
  uid: 67223ef4-a10e-4a9f-86c8-c72ff7c10f74
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello
      svc-name: hello-world-de
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-12-27T02:49:52+01:00"
      creationTimestamp: null
      labels:
        app: hello
        svc-name: hello-world-de
    spec:
      containers:
      - env:
        - name: WORLD
          valueFrom:
            configMapKeyRef:
              key: de
              name: hello-world-de
        image: adamgolab/hello-world:latest
        imagePullPolicy: Always
        name: hello-world-de
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

