# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: interview-task-es
    meta.helm.sh/release-namespace: interview
  creationTimestamp: "2022-12-26T23:50:08Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    svc-name: hello-world-es
  name: hello-world-es
  namespace: interview
  resourceVersion: "1135342"
  uid: 61852973-53cf-47f1-86dd-b343494b17ad
spec:
  clusterIP: 172.20.214.248
  clusterIPs:
  - 172.20.214.248
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    svc-name: hello-world-es
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
