apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
  template:
    metadata:
      labels:
        svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
        ports:
          - containerPort: {{.Values.service.targetPort}}
        env:
          - name: WORLD
            valueFrom:
              configMapKeyRef:
                key: {{.Values.deployment.depRegion}}
                name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}


